spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/main007?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: user   # todo : ec2환경 변수에 저장
    password: 1234   # todo : ec2환경 변수에 저장
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true;
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: yeogiyo007@gmail.com
    password: ${MAIL_SECRET_KEY} # todo : ec2환경 변수에 저장
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 271700253602-jg4ss6e6mpid627craeadftt8cjgeqa7.apps.googleusercontent.com
            clientSecret: 1
            scope:
              - email
              - profile
          naver:
            clientId: vslwDatKfTzz0X56xJYI
            clientSecret: 1
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://ec2-43-201-80-20.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/naver
          kakao:
            clientId: 749f3cb4d02e255ec0e216a37e19c700
            clientSecret: 1
            redirect-uri: http://ec2-43-201-80-20.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: Kakao


jwt:
  key:
    secret: ${JWT_SECRET_KEY}               # todo : ec2환경 변수에 저장
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

TMAP_APPKEY: l7xxc89bed3adc94451abfd7f0eebe850f9c   # todo : ec2환경 변수에 저장

cloud:
  aws:
    credentials:
      access-key: AKIAYPRKUHLUYUHTJRJB
      secret-key: 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
    s3:
      bucket: pre-032-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false