spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/main007
    username: user
    password: 1234

jwt:
  secret: dkssudgktpdy1qksrkqtmqslek2wjgmlsms3apdlsvmfhwprxm4007wh5dlqselk6
  access-token-expiration-minutes: 120
  refresh-token-expiration-minutes: 18000