spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/main007?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: user   # todo : ec2환경 변수에 저장
    password: 1234   # todo : ec2환경 변수에 저장

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true;

  mail:
    host: smtp.gmail.com
    port: 587
    username: yeogiyo007@gmail.com
    password: pibrnoalgjanhzwo # todo : ec2환경 변수에 저장
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB

jwt:
  key:
    secret: ${JWT_SECRET_KEY}               # todo : ec2환경 변수에 저장
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

TMAP_APPKEY: l7xxc89bed3adc94451abfd7f0eebe850f9c   # todo : ec2환경 변수에 저장