spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/main007?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: user
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true;
  mail:
    host: smtp.gmail.com
    port: 587
    username: yeogiyo007@gmail.com
    password: pibrnoalgjanhzwo # 환경변수로 변경 필요
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  key:
    secret: ${JWT_SECRET_KEY}               # 민감한 정보는 시스템 환경 변수에서 로드한다.
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

TMAP_APPKEY: l7xxc89bed3adc94451abfd7f0eebe850f9c