spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/main007?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: user
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true;
mail:
  host: smtp.gmail.com
  port: 587
  username: <내 구글 계정>
  password: <내 구글 계정 앱키>
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true